//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agenda()
        {
            this.Actas = new HashSet<Actas>();
        }
    
        public int IntAgendaID { get; set; }
        public string StrTitulo { get; set; }
        public string StrDescripcion { get; set; }
        public Nullable<System.DateTime> DatFechaInicial { get; set; }
        public Nullable<System.DateTime> DatFechaFinal { get; set; }
        public Nullable<bool> OpcAllDay { get; set; }
        public Nullable<bool> OpcEnviado { get; set; }
        public Nullable<bool> OpcCancelada { get; set; }
        public string StrHoras { get; set; }
        public int IntClienteID { get; set; }
        public int IntTipoEventoID { get; set; }
        public int IntUsuarioID { get; set; }
        public Nullable<int> IntActaID { get; set; }
        public Nullable<bool> OpcLunch { get; set; }
        public Nullable<System.DateTime> DatFechaIngreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actas> Actas { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual TipoEventos TipoEventos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
