//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsistentesActa
    {
        public int IntAsistenteID { get; set; }
        public string StrNombre { get; set; }
        public string StrProceso { get; set; }
        public Nullable<bool> OpcAsiste { get; set; }
        public Nullable<int> IntActaID { get; set; }
    
        public virtual Actas Actas { get; set; }
    }
}
