//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Agenda = new HashSet<Agenda>();
            this.Contactos = new HashSet<Contactos>();
            this.Contratos = new HashSet<Contratos>();
        }
    
        public int IntClienteID { get; set; }
        public string StrIdentificacion { get; set; }
        public Nullable<int> IntDV { get; set; }
        public string StrNombre { get; set; }
        public string StrDireccion { get; set; }
        public string StrEmail { get; set; }
        public Nullable<int> IntCiudadID { get; set; }
        public string StrTelefono { get; set; }
        public string StrPaginaWeb { get; set; }
        public System.DateTime DatFechaIngreso { get; set; }
        public Nullable<bool> OpcEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }
        public virtual Ciudades Ciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contactos> Contactos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contratos> Contratos { get; set; }
    }
}
