//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int IntID { get; set; }
        public string StrHoraInicial { get; set; }
        public string StrHoraFinal { get; set; }
        public string StrVistaAgenda { get; set; }
        public Nullable<int> IntDuracionDefault { get; set; }
        public string StrSMPTEmail { get; set; }
        public string StrSMTPPassword { get; set; }
        public Nullable<int> StrSMTPPort { get; set; }
        public string StrSMTPHost { get; set; }
        public Nullable<bool> OpcSMTPSSL { get; set; }
    }
}
