//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratos_Usuarios
    {
        public int IntRegistroID { get; set; }
        public int IntContratoID { get; set; }
        public int IntUsuarioID { get; set; }
    
        public virtual Contratos Contratos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
