//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contratos()
        {
            this.Contratos_SistemasDeGestion = new HashSet<Contratos_SistemasDeGestion>();
            this.Contratos_Usuarios = new HashSet<Contratos_Usuarios>();
        }
    
        public int IntContratoID { get; set; }
        public Nullable<int> IntNumeroContrato { get; set; }
        public System.DateTime DatFechaInicial { get; set; }
        public System.DateTime DatFechaFinal { get; set; }
        public Nullable<int> IntHoras { get; set; }
        public Nullable<int> IntValor { get; set; }
        public string StrEmail { get; set; }
        public Nullable<int> IntClienteID { get; set; }
        public Nullable<bool> OpcEstado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contratos_SistemasDeGestion> Contratos_SistemasDeGestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contratos_Usuarios> Contratos_Usuarios { get; set; }
    }
}
