//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public int IntContactoID { get; set; }
        public string StrNombre { get; set; }
        public string StrCargo { get; set; }
        public string StrTelefonoFijo { get; set; }
        public string StrCelular { get; set; }
        public string StrEmail { get; set; }
        public Nullable<int> IntClienteID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
