//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class datosNetEntities : DbContext
    {
        public datosNetEntities()
            : base("name=datosNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actas> Actas { get; set; }
        public virtual DbSet<ActividadesActa> ActividadesActa { get; set; }
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<AsistentesActa> AsistentesActa { get; set; }
        public virtual DbSet<Ciudades> Ciudades { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<Contratos> Contratos { get; set; }
        public virtual DbSet<Contratos_SistemasDeGestion> Contratos_SistemasDeGestion { get; set; }
        public virtual DbSet<Contratos_Usuarios> Contratos_Usuarios { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<LogsEx> LogsEx { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<Procesos> Procesos { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Roles_Modulos> Roles_Modulos { get; set; }
        public virtual DbSet<SistemasDeGestion> SistemasDeGestion { get; set; }
        public virtual DbSet<TemasActa> TemasActa { get; set; }
        public virtual DbSet<TipoEventos> TipoEventos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
