//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsEx
    {
        public int IntLogID { get; set; }
        public Nullable<int> IntUsuarioID { get; set; }
        public string StrMensaje { get; set; }
        public string StrRecurso { get; set; }
        public Nullable<System.DateTime> DatFecha { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
