//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_Modulos
    {
        public int IntRegistroID { get; set; }
        public int IntRolID { get; set; }
        public int IntModuloID { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
