//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemasActa
    {
        public int IntTemaID { get; set; }
        public Nullable<int> IntActaID { get; set; }
        public string StrDescripcion { get; set; }
        public string StrResponsable { get; set; }
        public string StrDesarrollo { get; set; }
    
        public virtual Actas Actas { get; set; }
    }
}
