//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoEventos()
        {
            this.Agenda = new HashSet<Agenda>();
        }
    
        public int IntTipoEventoID { get; set; }
        public string StrCodigo { get; set; }
        public string StrDescripcion { get; set; }
        public Nullable<bool> OpcSoporte { get; set; }
        public Nullable<bool> OpcAlerta { get; set; }
        public Nullable<bool> OpcEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }
    }
}
