//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Agenda = new HashSet<Agenda>();
            this.Contratos_Usuarios = new HashSet<Contratos_Usuarios>();
            this.LogsEx = new HashSet<LogsEx>();
        }
    
        public int IntUsuarioID { get; set; }
        public Nullable<int> IntRolID { get; set; }
        public string StrCodigo { get; set; }
        public string StrNombre { get; set; }
        public string StrClave { get; set; }
        public string StrEmail { get; set; }
        public Nullable<int> IntCiudadID { get; set; }
        public string StrDireccion { get; set; }
        public string StrTelefonoFijo { get; set; }
        public string StrCelular { get; set; }
        public string StrColor { get; set; }
        public bool OpcEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }
        public virtual Ciudades Ciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contratos_Usuarios> Contratos_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogsEx> LogsEx { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
