//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Across.ArchivosDeRecurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoAusentismo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoAusentismo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Across.ArchivosDeRecurso.RecursoAusentismo", typeof(RecursoAusentismo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no fue encontrado en la base de datos, revisar por favor..
        /// </summary>
        public static string msnAusentismoNoEncontrado {
            get {
                return ResourceManager.GetString("msnAusentismoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El empleado tiene registrada una incapacidad en las fechas indicadas..
        /// </summary>
        public static string msnEmpleadoConAusentismo {
            get {
                return ResourceManager.GetString("msnEmpleadoConAusentismo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El empleado tiene una prorroga de la incapacidad en las fechas indicadas..
        /// </summary>
        public static string msnEmpleadoConProrroga {
            get {
                return ResourceManager.GetString("msnEmpleadoConProrroga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La prórroga no puede ser anterior a la incapacidad..
        /// </summary>
        public static string msnProrrogaMenosAIncapacidad {
            get {
                return ResourceManager.GetString("msnProrrogaMenosAIncapacidad", resourceCulture);
            }
        }
    }
}
