//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Across.ArchivosDeRecurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoProcesos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoProcesos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Across.ArchivosDeRecurso.RecursoProcesos", typeof(RecursoProcesos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El numeral seleccionado ya fue agregado a este proceso, intente con otro numeral diferente..
        /// </summary>
        public static string msnNumeralDuplicadoEnProceso {
            get {
                return ResourceManager.GetString("msnNumeralDuplicadoEnProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso {0} no contiene listas de verificación..
        /// </summary>
        public static string msnProcesoSinListaDeVerificacion {
            get {
                return ResourceManager.GetString("msnProcesoSinListaDeVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso con código {0} ya existe. El registro no fue guardado..
        /// </summary>
        public static string msnRegistroYaExiste {
            get {
                return ResourceManager.GetString("msnRegistroYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso {0} se encuentra relacionado en una auditoría. El registro no puede ser eliminado porque se perderia el historial, intente inactivarlo..
        /// </summary>
        public static string msnRelacionConAuditoria {
            get {
                return ResourceManager.GetString("msnRelacionConAuditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso {0} se encuentra relacionado en el detalle de una auditoría. El registro no puede ser eliminado porque se perderia el historial, intente inactivarlo..
        /// </summary>
        public static string msnRelacionConAuditoriaDetalle {
            get {
                return ResourceManager.GetString("msnRelacionConAuditoriaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso {0} se encuentra relacionado en un empleado. El registro no puede ser eliminado porque se perderia el historial, intente inactivarlo..
        /// </summary>
        public static string msnRelacionConEmpleados {
            get {
                return ResourceManager.GetString("msnRelacionConEmpleados", resourceCulture);
            }
        }
    }
}
