//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Across.ArchivosDeRecurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Across.ArchivosDeRecurso.RecursoCommon", typeof(RecursoCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo seleccionado no es válido, intentelo nuevamente..
        /// </summary>
        public static string msnArchivoNoValido {
            get {
                return ResourceManager.GetString("msnArchivoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo no contiene datos..
        /// </summary>
        public static string msnArchivoSinDatos {
            get {
                return ResourceManager.GetString("msnArchivoSinDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hora final debe ser superior a la hora inicial..
        /// </summary>
        public static string msnHoraInicialMayorHoraFinal {
            get {
                return ResourceManager.GetString("msnHoraInicialMayorHoraFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El elemento indicado no se encontró en la base de datos. .
        /// </summary>
        public static string msnRegistroNoEncontrado {
            get {
                return ResourceManager.GetString("msnRegistroNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código {0} ya existe. El registro actual no fue guardado..
        /// </summary>
        public static string msnRegistroYaExiste {
            get {
                return ResourceManager.GetString("msnRegistroYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código {0} se encuentra relacionado en un registro de ausentismo. El registro actual no fue eliminado..
        /// </summary>
        public static string msnRelacionConAusentismo {
            get {
                return ResourceManager.GetString("msnRelacionConAusentismo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código {0} se encuentra relacionado en un empleado. El registro actual no fue eliminado..
        /// </summary>
        public static string msnRelacionConEmpleados {
            get {
                return ResourceManager.GetString("msnRelacionConEmpleados", resourceCulture);
            }
        }
    }
}
