//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Across.ArchivosDeRecurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoManage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoManage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Across.ArchivosDeRecurso.RecursoManage", typeof(RecursoManage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al actualizar el registro en la tabla de AspNetUsers..
        /// </summary>
        public static string msnErrorAlActualizarAspNetUsers {
            get {
                return ResourceManager.GetString("msnErrorAlActualizarAspNetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al actualizar el registro en la tabla de TercerosUsuarios..
        /// </summary>
        public static string msnErrorAlActualizarTercerosUsuarios {
            get {
                return ResourceManager.GetString("msnErrorAlActualizarTercerosUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El perfil no contiene imagen..
        /// </summary>
        public static string msnPerfilSinImagen {
            get {
                return ResourceManager.GetString("msnPerfilSinImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email {0} no aparece registrado en el cliente. Por favor revisar..
        /// </summary>
        public static string msnTerceroUsuarioNoExiste {
            get {
                return ResourceManager.GetString("msnTerceroUsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email {0} no aparece registrado en nuestra base de datos. Ponte en contacto con el administrador del software..
        /// </summary>
        public static string msnUsuarioNoExiste {
            get {
                return ResourceManager.GetString("msnUsuarioNoExiste", resourceCulture);
            }
        }
    }
}
