//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Across.ArchivosDeRecurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoTerceros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoTerceros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Across.ArchivosDeRecurso.RecursoTerceros", typeof(RecursoTerceros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se detectó una inconsistencia al guardar los roles del tercero..
        /// </summary>
        public static string msnErrorEnRoles {
            get {
                return ResourceManager.GetString("msnErrorEnRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tercero ya tiene asignada esa norma, intente con otra diferente..
        /// </summary>
        public static string msnNormaDuplicada {
            get {
                return ResourceManager.GetString("msnNormaDuplicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tercero ya tiene asignado ese permiso, intente con otro diferente..
        /// </summary>
        public static string msnRolDuplicado {
            get {
                return ResourceManager.GetString("msnRolDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La identificación indicada ya existe, intente con otra diferente..
        /// </summary>
        public static string msnTerceroExiste {
            get {
                return ResourceManager.GetString("msnTerceroExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tercero no existe..
        /// </summary>
        public static string msnTerceroNoExiste {
            get {
                return ResourceManager.GetString("msnTerceroNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa no tiene asignado NIVEL en los sitemas de gestión..
        /// </summary>
        public static string msnTerceroSinNivel {
            get {
                return ResourceManager.GetString("msnTerceroSinNivel", resourceCulture);
            }
        }
    }
}
