//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Across.ArchivosDeRecurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoAuditorias {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoAuditorias() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Across.ArchivosDeRecurso.RecursoAuditorias", typeof(RecursoAuditorias).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ya tiene asignado un evento a esa hora..
        /// </summary>
        public static string msnAperturaCierreYaExiste {
            get {
                return ResourceManager.GetString("msnAperturaCierreYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La programación para auditar el proceso {0} ya fue generada. Por favor revise nuevamente..
        /// </summary>
        public static string msnAuditoriaDetalleYaExisteParaElProceso {
            get {
                return ResourceManager.GetString("msnAuditoriaDetalleYaExisteParaElProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tercero ya tiene una auditoria programada entre {0} y {1}..
        /// </summary>
        public static string msnAuditoriaYaExiste {
            get {
                return ResourceManager.GetString("msnAuditoriaYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de la auditoria debe estár entre {0} y {1}.
        /// </summary>
        public static string msnFechaFueraDeRango {
            get {
                return ResourceManager.GetString("msnFechaFueraDeRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hora final no puede ser anterior a la hora inicial..
        /// </summary>
        public static string msnHoraFinalMenorAhoraInicial {
            get {
                return ResourceManager.GetString("msnHoraFinalMenorAhoraInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tercero está relacionado en Auditorías, por lo tanto no se puede eliminar..
        /// </summary>
        public static string msnTerceroConAuditoria {
            get {
                return ResourceManager.GetString("msnTerceroConAuditoria", resourceCulture);
            }
        }
    }
}
