//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Across.ArchivosDeRecurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoUsuarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoUsuarios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Across.ArchivosDeRecurso.RecursoUsuarios", typeof(RecursoUsuarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha presentando un error en la autenticación. Valide que su correo esté bien escrito..
        /// </summary>
        public static string msnErrorAutenticacionExterna {
            get {
                return ResourceManager.GetString("msnErrorAutenticacionExterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las instrucciones para recuperar su contraseña han sido enviadas a su correo electrónico..
        /// </summary>
        public static string msnRecuperarContraseña {
            get {
                return ResourceManager.GetString("msnRecuperarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se encuentra bloqueado..
        /// </summary>
        public static string msnUsuarioBloqueado {
            get {
                return ResourceManager.GetString("msnUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email asociado al usuario ya existe. Intente con otro correo diferente..
        /// </summary>
        public static string msnUsuarioExiste {
            get {
                return ResourceManager.GetString("msnUsuarioExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos de acceso son incorrectos..
        /// </summary>
        public static string msnUsuarioInvalido {
            get {
                return ResourceManager.GetString("msnUsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario con el email {0} no fue encontrado en la base de datos. Comuniquese con un usuario administrador..
        /// </summary>
        public static string msnUsuarioNoEncontrado {
            get {
                return ResourceManager.GetString("msnUsuarioNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario aun no ha sido activado en la aplicación. Contacte a su asesor de Gestión Integral SGI..
        /// </summary>
        public static string msnUsuarioSinAsignar {
            get {
                return ResourceManager.GetString("msnUsuarioSinAsignar", resourceCulture);
            }
        }
    }
}
