//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Across.ArchivosDeRecurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoSeguridad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoSeguridad() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Across.ArchivosDeRecurso.RecursoSeguridad", typeof(RecursoSeguridad).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe confirmar su cuenta en su correo electrónico para acceder a la aplicación..
        /// </summary>
        public static string msnConfirmarCuentaDeCorreo {
            get {
                return ResourceManager.GetString("msnConfirmarCuentaDeCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las instrucciones para recuperar su contraseña han sido enviadas a su correo electrónico..
        /// </summary>
        public static string msnConfirmarEmail {
            get {
                return ResourceManager.GetString("msnConfirmarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contraseña fue restablecida exitosamente..
        /// </summary>
        public static string msnContraseñaRestablecida {
            get {
                return ResourceManager.GetString("msnContraseñaRestablecida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos suministrados no son correctos, intentelo nuevamente..
        /// </summary>
        public static string msnCredencialesNoValidas {
            get {
                return ResourceManager.GetString("msnCredencialesNoValidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cambio de contraseña NO ha sido exitoso, asegurese que haya escrito bien el correo electrónico..
        /// </summary>
        public static string msnErrorCambioContraseña {
            get {
                return ResourceManager.GetString("msnErrorCambioContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al hacer el Login..
        /// </summary>
        public static string msnLogeoFallido {
            get {
                return ResourceManager.GetString("msnLogeoFallido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se encuentra bloqueado..
        /// </summary>
        public static string msnUsuarioBloqueado {
            get {
                return ResourceManager.GetString("msnUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no existe en la base de datos..
        /// </summary>
        public static string msnUsuarioNoExiste {
            get {
                return ResourceManager.GetString("msnUsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya se encuentra registrado, haga click en el enlace Recuperar Contraseña de la ventana de inicio para obtener una nueva contraseña..
        /// </summary>
        public static string msnUsuarioYaEstaRegistrado {
            get {
                return ResourceManager.GetString("msnUsuarioYaEstaRegistrado", resourceCulture);
            }
        }
    }
}
