//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetTerceroRoles
    {
        public int IntAspNetTerceroRolesID { get; set; }
        public int IntTerceroID { get; set; }
        public string IntRolID { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Terceros Terceros { get; set; }
    }
}
