//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditorias_Normas
    {
        public int IntID { get; set; }
        public int IntAuditoriaID { get; set; }
        public int IntNormaID { get; set; }
    
        public virtual Normas Normas { get; set; }
        public virtual Auditorias Auditorias { get; set; }
    }
}
