//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriasDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditoriasDetalle()
        {
            this.ListasDeVerificacion = new HashSet<ListasDeVerificacion>();
        }
    
        public int IntAuditoriaDetalleID { get; set; }
        public int IntAuditoriaID { get; set; }
        public int IntProcesoID { get; set; }
        public string StrModalidad { get; set; }
        public string StrAuditado { get; set; }
        public string StrAuditor { get; set; }
        public System.DateTime DatFechaInicial { get; set; }
        public System.DateTime DatFechaFinal { get; set; }
        public string StrDetalle { get; set; }
        public Nullable<System.DateTime> DatFechaProgramacion { get; set; }
    
        public virtual Auditorias Auditorias { get; set; }
        public virtual Procesos Procesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListasDeVerificacion> ListasDeVerificacion { get; set; }
    }
}
