//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auditorias()
        {
            this.Auditorias_Normas = new HashSet<Auditorias_Normas>();
            this.Auditorias_Procesos = new HashSet<Auditorias_Procesos>();
            this.AuditoriasDetalleAC = new HashSet<AuditoriasDetalleAC>();
            this.AuditoriasDetalle = new HashSet<AuditoriasDetalle>();
        }
    
        public int IntAuditoriaID { get; set; }
        public int IntConsecutivo { get; set; }
        public System.DateTime DatFechaInicial { get; set; }
        public System.DateTime DatFechaFinal { get; set; }
        public string StrCodigo { get; set; }
        public string StrVersion { get; set; }
        public Nullable<System.DateTime> DatFechaVersion { get; set; }
        public string StrObjetivo { get; set; }
        public string StrAlcance { get; set; }
        public string StrIntegranteCopasst { get; set; }
        public string StrRepresentanteLegal { get; set; }
        public string StrFortalezas { get; set; }
        public string StrConclusiones { get; set; }
        public string StrUsuarioID { get; set; }
        public string StrUsuarioFirma { get; set; }
        public Nullable<bool> BitFirma { get; set; }
        public Nullable<bool> BitEstado { get; set; }
        public int IntTerceroClienteID { get; set; }
        public Nullable<System.DateTime> DatFechaElaboracionInforme { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditorias_Normas> Auditorias_Normas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditorias_Procesos> Auditorias_Procesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriasDetalleAC> AuditoriasDetalleAC { get; set; }
        public virtual Terceros_Clientes Terceros_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriasDetalle> AuditoriasDetalle { get; set; }
    }
}
