//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ausentismo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ausentismo()
        {
            this.AusentismoProrrogas = new HashSet<AusentismoProrrogas>();
            this.AusentismoTiempos = new HashSet<AusentismoTiempos>();
        }
    
        public int IntAusentismoID { get; set; }
        public System.DateTime DatFechaInicial { get; set; }
        public System.DateTime DatFechaFinal { get; set; }
        public string StrObservaciones { get; set; }
        public int IntTerceroID { get; set; }
        public int IntEmpleadoID { get; set; }
        public int IntTipoEventoAusentismoID { get; set; }
        public int IntDiagnosticoID { get; set; }
    
        public virtual Diagnosticos Diagnosticos { get; set; }
        public virtual TipoEventosAusentismo TipoEventosAusentismo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AusentismoProrrogas> AusentismoProrrogas { get; set; }
        public virtual Terceros Terceros { get; set; }
        public virtual Empleados Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AusentismoTiempos> AusentismoTiempos { get; set; }
    }
}
