//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AusentismoVariables
    {
        public int IntAusentismoVariablesID { get; set; }
        public Nullable<short> IntAno { get; set; }
        public Nullable<byte> TIntPeriodo { get; set; }
        public Nullable<int> IntTotalEmpleados { get; set; }
        public Nullable<int> IntHorasHombre { get; set; }
        public int IntTerceroID { get; set; }
        public Nullable<int> IntHorasHombreProgramadas { get; set; }
    
        public virtual Terceros Terceros { get; set; }
    }
}
