//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AusentismoIndicadores_InformacionPorEmpresa
    {
        public string StrId { get; set; }
        public string StrAusentismoIndicadoresID { get; set; }
        public int IntTerceroID { get; set; }
        public string StrProceso { get; set; }
        public string StrCargos { get; set; }
        public string StrResponsable { get; set; }
        public string StrTipoGrafico { get; set; }
        public string StrFrecuencia { get; set; }
        public int IntMeta_1 { get; set; }
        public int IntMeta_2 { get; set; }
        public int IntMeta_3 { get; set; }
        public int IntMeta_4 { get; set; }
        public int IntMeta_5 { get; set; }
        public int IntMeta_6 { get; set; }
        public int IntMeta_7 { get; set; }
        public int IntMeta_8 { get; set; }
        public int IntMeta_9 { get; set; }
        public int IntMeta_10 { get; set; }
        public int IntMeta_11 { get; set; }
        public int IntMeta_12 { get; set; }
    
        public virtual AusentismoIndicadores AusentismoIndicadores { get; set; }
    }
}
