//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AusentismoProrrogas
    {
        public int IntProrrogaID { get; set; }
        public int IntAusentismoID { get; set; }
        public System.DateTime DatFechaInicial { get; set; }
        public System.DateTime DatFechaFinal { get; set; }
    
        public virtual Ausentismo Ausentismo { get; set; }
    }
}
