//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AusentismoIndicadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AusentismoIndicadores()
        {
            this.AusentismoIndicadores_InformacionPorEmpresa = new HashSet<AusentismoIndicadores_InformacionPorEmpresa>();
        }
    
        public string StrId { get; set; }
        public string StrCodigo { get; set; }
        public string StrNombreIndicador { get; set; }
        public string StrTipoEventoAusentismo { get; set; }
        public string StrFormula { get; set; }
        public string StrFuente { get; set; }
        public string StrObjetivo { get; set; }
        public int IntOrdenamiento { get; set; }
        public string StrObservaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AusentismoIndicadores_InformacionPorEmpresa> AusentismoIndicadores_InformacionPorEmpresa { get; set; }
    }
}
