//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AusentismoTiempos
    {
        public int IntAusentismoTiempoID { get; set; }
        public short IntAño { get; set; }
        public byte TIntPeriodo { get; set; }
        public int IntDiasIncapacidad { get; set; }
        public int IntDiasProrroga { get; set; }
        public int IntAusentismoID { get; set; }
        public int IntEmpleadoID { get; set; }
        public int IntTerceroID { get; set; }
        public int IntTipoEventoAusentismoID { get; set; }
        public int IntDiagnosticoID { get; set; }
        public int IntAreaID { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Ausentismo Ausentismo { get; set; }
        public virtual AusentismoTiempos AusentismoTiempos1 { get; set; }
        public virtual AusentismoTiempos AusentismoTiempos2 { get; set; }
        public virtual Diagnosticos Diagnosticos { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Terceros Terceros { get; set; }
        public virtual TipoEventosAusentismo TipoEventosAusentismo { get; set; }
    }
}
