//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentrosDeTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentrosDeTrabajo()
        {
            this.Empleados = new HashSet<Empleados>();
        }
    
        public int IntCentroDeTrabajoID { get; set; }
        public string StrCodigo { get; set; }
        public string StrDescripcion { get; set; }
        public Nullable<int> IntTerceroID { get; set; }
        public Nullable<bool> BitActivo { get; set; }
    
        public virtual Terceros Terceros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
    }
}
