//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionPorTercero
    {
        public int IntConfiguracionID { get; set; }
        public int IntTerceroID { get; set; }
        public short SIntAusentismoBajo { get; set; }
        public short SIntAusentismoMedio { get; set; }
        public short SIntAusentismoAlto { get; set; }
    
        public virtual Terceros Terceros { get; set; }
    }
}
