//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestioni_consultorNetEntities : DbContext
    {
        public gestioni_consultorNetEntities()
            : base("name=gestioni_consultorNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetTerceroRoles> AspNetTerceroRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Auditorias_Normas> Auditorias_Normas { get; set; }
        public virtual DbSet<Auditorias_Procesos> Auditorias_Procesos { get; set; }
        public virtual DbSet<AuditoriasDetalleAC> AuditoriasDetalleAC { get; set; }
        public virtual DbSet<AusentismoProrrogas> AusentismoProrrogas { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<CentrosDeTrabajo> CentrosDeTrabajo { get; set; }
        public virtual DbSet<ConfiguracionPorTercero> ConfiguracionPorTercero { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Diagnosticos> Diagnosticos { get; set; }
        public virtual DbSet<ElementosComunes> ElementosComunes { get; set; }
        public virtual DbSet<ElementosComunes_Detalle> ElementosComunes_Detalle { get; set; }
        public virtual DbSet<ElementosComunes_Detalle_Numerales> ElementosComunes_Detalle_Numerales { get; set; }
        public virtual DbSet<ElementosComunes_Normas> ElementosComunes_Normas { get; set; }
        public virtual DbSet<Escolaridades> Escolaridades { get; set; }
        public virtual DbSet<EstadosCiviles> EstadosCiviles { get; set; }
        public virtual DbSet<Estratos> Estratos { get; set; }
        public virtual DbSet<Fondos> Fondos { get; set; }
        public virtual DbSet<LogsException> LogsException { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<ModulosDetalle> ModulosDetalle { get; set; }
        public virtual DbSet<ModulosPorRol> ModulosPorRol { get; set; }
        public virtual DbSet<Normas> Normas { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Terceros_Normas> Terceros_Normas { get; set; }
        public virtual DbSet<TercerosUsuarios> TercerosUsuarios { get; set; }
        public virtual DbSet<TipoEventosAusentismo> TipoEventosAusentismo { get; set; }
        public virtual DbSet<TipoIdentificacion> TipoIdentificacion { get; set; }
        public virtual DbSet<TiposContrato> TiposContrato { get; set; }
        public virtual DbSet<TiposFondo> TiposFondo { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
        public virtual DbSet<Numerales> Numerales { get; set; }
        public virtual DbSet<PlantillasListasDeVerificacion_Numerales> PlantillasListasDeVerificacion_Numerales { get; set; }
        public virtual DbSet<Ausentismo> Ausentismo { get; set; }
        public virtual DbSet<Terceros_SistemasDeGestion> Terceros_SistemasDeGestion { get; set; }
        public virtual DbSet<Terceros_SistemasDeGestion_Normas> Terceros_SistemasDeGestion_Normas { get; set; }
        public virtual DbSet<Fases> Fases { get; set; }
        public virtual DbSet<Niveles> Niveles { get; set; }
        public virtual DbSet<DocumentosDiagnosticoDetalle> DocumentosDiagnosticoDetalle { get; set; }
        public virtual DbSet<DocumentosDiagnosticoPasos> DocumentosDiagnosticoPasos { get; set; }
        public virtual DbSet<DocumentosDiagnosticoPasos_Criterios> DocumentosDiagnosticoPasos_Criterios { get; set; }
        public virtual DbSet<DocumentosDiagnosticoPasos_DocumentoEvidencia> DocumentosDiagnosticoPasos_DocumentoEvidencia { get; set; }
        public virtual DbSet<DocumentosDiagnosticoPasos_Niveles> DocumentosDiagnosticoPasos_Niveles { get; set; }
        public virtual DbSet<DocumentosDiagnostico> DocumentosDiagnostico { get; set; }
        public virtual DbSet<SistemasDeGestion> SistemasDeGestion { get; set; }
        public virtual DbSet<NivelesDeRiesgo> NivelesDeRiesgo { get; set; }
        public virtual DbSet<DocumentosDiagnosticoDetalle_PlanesDeAccion> DocumentosDiagnosticoDetalle_PlanesDeAccion { get; set; }
        public virtual DbSet<Procesos> Procesos { get; set; }
        public virtual DbSet<Ciudades> Ciudades { get; set; }
        public virtual DbSet<Auditorias> Auditorias { get; set; }
        public virtual DbSet<PlantillasListasDeVerificacionDetalle> PlantillasListasDeVerificacionDetalle { get; set; }
        public virtual DbSet<Terceros> Terceros { get; set; }
        public virtual DbSet<Terceros_Clientes> Terceros_Clientes { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<AusentismoTiempos> AusentismoTiempos { get; set; }
        public virtual DbSet<ListasDeVerificacion_Requisitos> ListasDeVerificacion_Requisitos { get; set; }
        public virtual DbSet<AusentismoIndicadores> AusentismoIndicadores { get; set; }
        public virtual DbSet<AusentismoIndicadores_InformacionPorEmpresa> AusentismoIndicadores_InformacionPorEmpresa { get; set; }
        public virtual DbSet<AusentismoVariables> AusentismoVariables { get; set; }
        public virtual DbSet<AuditoriasDetalle> AuditoriasDetalle { get; set; }
        public virtual DbSet<ListasDeVerificacion> ListasDeVerificacion { get; set; }
    }
}
