//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosDiagnosticoPasos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentosDiagnosticoPasos()
        {
            this.DocumentosDiagnosticoDetalle = new HashSet<DocumentosDiagnosticoDetalle>();
            this.DocumentosDiagnosticoPasos_Criterios = new HashSet<DocumentosDiagnosticoPasos_Criterios>();
            this.DocumentosDiagnosticoPasos_DocumentoEvidencia = new HashSet<DocumentosDiagnosticoPasos_DocumentoEvidencia>();
            this.DocumentosDiagnosticoPasos_Niveles = new HashSet<DocumentosDiagnosticoPasos_Niveles>();
        }
    
        public string StrPasoID { get; set; }
        public string StrFaseID { get; set; }
        public string StrSistemaDeGestionID { get; set; }
        public byte IntNumero { get; set; }
        public string StrRequisito { get; set; }
        public bool BitActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDiagnosticoDetalle> DocumentosDiagnosticoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDiagnosticoPasos_Criterios> DocumentosDiagnosticoPasos_Criterios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDiagnosticoPasos_DocumentoEvidencia> DocumentosDiagnosticoPasos_DocumentoEvidencia { get; set; }
        public virtual Fases Fases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDiagnosticoPasos_Niveles> DocumentosDiagnosticoPasos_Niveles { get; set; }
        public virtual SistemasDeGestion SistemasDeGestion { get; set; }
    }
}
