//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosDiagnostico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentosDiagnostico()
        {
            this.DocumentosDiagnosticoDetalle = new HashSet<DocumentosDiagnosticoDetalle>();
        }
    
        public string StrDocumentoID { get; set; }
        public int IntTerceroID { get; set; }
        public System.DateTime DatFechaElaboracion { get; set; }
        public string StrUsuarioID { get; set; }
        public bool BitFinalizado { get; set; }
        public string StrSistemaDeGestionID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual SistemasDeGestion SistemasDeGestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDiagnosticoDetalle> DocumentosDiagnosticoDetalle { get; set; }
        public virtual Terceros Terceros { get; set; }
    }
}
