//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosDiagnosticoDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentosDiagnosticoDetalle()
        {
            this.DocumentosDiagnosticoDetalle_PlanesDeAccion = new HashSet<DocumentosDiagnosticoDetalle_PlanesDeAccion>();
        }
    
        public string StrDocumentoDetalleID { get; set; }
        public string StrDocumentoID { get; set; }
        public string StrPasoID { get; set; }
    
        public virtual DocumentosDiagnosticoPasos DocumentosDiagnosticoPasos { get; set; }
        public virtual DocumentosDiagnostico DocumentosDiagnostico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDiagnosticoDetalle_PlanesDeAccion> DocumentosDiagnosticoDetalle_PlanesDeAccion { get; set; }
    }
}
