//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosDiagnosticoDetalle_PlanesDeAccion
    {
        public string StrCalificacionID { get; set; }
        public string StrDocumentoDetalleID { get; set; }
        public string StrCriterioID { get; set; }
        public bool BitAplica { get; set; }
        public Nullable<bool> BitSeEvidencia { get; set; }
        public string StrComoSeEvidencia { get; set; }
        public string StrPlanDeAccion { get; set; }
        public string StrResponsable { get; set; }
        public Nullable<System.DateTime> DatFecha { get; set; }
        public Nullable<System.DateTime> DatFechaCalificacion { get; set; }
    
        public virtual DocumentosDiagnosticoDetalle DocumentosDiagnosticoDetalle { get; set; }
        public virtual DocumentosDiagnosticoPasos_Criterios DocumentosDiagnosticoPasos_Criterios { get; set; }
    }
}
