//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosDiagnosticoPasos_Criterios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentosDiagnosticoPasos_Criterios()
        {
            this.DocumentosDiagnosticoDetalle_PlanesDeAccion = new HashSet<DocumentosDiagnosticoDetalle_PlanesDeAccion>();
        }
    
        public string StrCriterioID { get; set; }
        public string StrDescripcion { get; set; }
        public string StrPasoID { get; set; }
        public string StrEvidenciaID { get; set; }
        public Nullable<byte> IntOrden { get; set; }
        public bool BitActivo { get; set; }
    
        public virtual DocumentosDiagnosticoPasos DocumentosDiagnosticoPasos { get; set; }
        public virtual DocumentosDiagnosticoPasos_DocumentoEvidencia DocumentosDiagnosticoPasos_DocumentoEvidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDiagnosticoDetalle_PlanesDeAccion> DocumentosDiagnosticoDetalle_PlanesDeAccion { get; set; }
    }
}
