//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosDiagnosticoPasos_DocumentoEvidencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentosDiagnosticoPasos_DocumentoEvidencia()
        {
            this.DocumentosDiagnosticoPasos_Criterios = new HashSet<DocumentosDiagnosticoPasos_Criterios>();
        }
    
        public string StrEvidenciaID { get; set; }
        public string StrPasoID { get; set; }
        public string StrDescripcion { get; set; }
        public bool BitActivo { get; set; }
    
        public virtual DocumentosDiagnosticoPasos DocumentosDiagnosticoPasos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDiagnosticoPasos_Criterios> DocumentosDiagnosticoPasos_Criterios { get; set; }
    }
}
