//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosDiagnosticoPasos_Niveles
    {
        public string StrRegistroID { get; set; }
        public string StrPasoID { get; set; }
        public string StrNivelID { get; set; }
    
        public virtual DocumentosDiagnosticoPasos DocumentosDiagnosticoPasos { get; set; }
        public virtual Niveles Niveles { get; set; }
    }
}
