//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementosComunes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElementosComunes()
        {
            this.ElementosComunes_Detalle = new HashSet<ElementosComunes_Detalle>();
            this.ElementosComunes_Normas = new HashSet<ElementosComunes_Normas>();
        }
    
        public int IntElementoComunID { get; set; }
        public string StrDescripcion { get; set; }
        public bool BitActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementosComunes_Detalle> ElementosComunes_Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementosComunes_Normas> ElementosComunes_Normas { get; set; }
    }
}
