//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementosComunes_Detalle_Numerales
    {
        public int IntRegistroID { get; set; }
        public int IntDetalleID { get; set; }
        public int IntNumeralID { get; set; }
    
        public virtual ElementosComunes_Detalle ElementosComunes_Detalle { get; set; }
        public virtual Numerales Numerales { get; set; }
    }
}
