//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementosComunes_Detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElementosComunes_Detalle()
        {
            this.ElementosComunes_Detalle_Numerales = new HashSet<ElementosComunes_Detalle_Numerales>();
        }
    
        public int IntDetalleID { get; set; }
        public int IntElementoComunID { get; set; }
        public string StrInterpretacion { get; set; }
        public bool BitActivo { get; set; }
    
        public virtual ElementosComunes ElementosComunes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementosComunes_Detalle_Numerales> ElementosComunes_Detalle_Numerales { get; set; }
    }
}
