//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Ausentismo = new HashSet<Ausentismo>();
            this.AusentismoTiempos = new HashSet<AusentismoTiempos>();
        }
    
        public int IntEmpleadoID { get; set; }
        public int IntTerceroID { get; set; }
        public string StrIdentificacion { get; set; }
        public Nullable<int> IntTipoIdentificacion { get; set; }
        public string StrPrimerApellido { get; set; }
        public string StrSegundoApellido { get; set; }
        public string StrPrimerNombre { get; set; }
        public string StrSegundoNombre { get; set; }
        public string StrNombreCompleto { get; set; }
        public string StrRutaImagen { get; set; }
        public string StrGenero { get; set; }
        public string StrNacionalidad { get; set; }
        public Nullable<int> IntCentroDeTrabajo { get; set; }
        public Nullable<System.DateTime> DatFechaNacimiento { get; set; }
        public Nullable<System.DateTime> DatFechaIngreso { get; set; }
        public Nullable<int> IntCiudadNacimiento { get; set; }
        public Nullable<int> IntCiudadLabora { get; set; }
        public Nullable<int> IntCiudadResidencia { get; set; }
        public string StrDireccionResidencia { get; set; }
        public string StrTelefono { get; set; }
        public string StrCelular { get; set; }
        public string StrEmail { get; set; }
        public Nullable<int> IntCargo { get; set; }
        public Nullable<int> IntTurno { get; set; }
        public Nullable<int> IntAreaID { get; set; }
        public Nullable<int> IntARL { get; set; }
        public Nullable<int> IntEPS { get; set; }
        public Nullable<int> IntAFP { get; set; }
        public Nullable<int> IntTipoContrato { get; set; }
        public Nullable<int> IntSalario { get; set; }
        public Nullable<int> IntEscolaridad { get; set; }
        public Nullable<int> IntEstadoCivil { get; set; }
        public Nullable<byte> TIntNumeroHijos { get; set; }
        public string StrPersonasACargo { get; set; }
        public Nullable<byte> TIntEstrato { get; set; }
        public string StrGrupoSanguineo { get; set; }
        public string StrCondiciones { get; set; }
        public string StrAlergias { get; set; }
        public string StrMedicinas { get; set; }
        public string StrContacto { get; set; }
        public string StrParentesco { get; set; }
        public string StrTelefonoContacto { get; set; }
        public Nullable<bool> BitActivo { get; set; }
    
        public virtual Areas Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ausentismo> Ausentismo { get; set; }
        public virtual Cargos Cargos { get; set; }
        public virtual CentrosDeTrabajo CentrosDeTrabajo { get; set; }
        public virtual Ciudades Ciudades { get; set; }
        public virtual Ciudades Ciudades1 { get; set; }
        public virtual Ciudades Ciudades2 { get; set; }
        public virtual Escolaridades Escolaridades { get; set; }
        public virtual EstadosCiviles EstadosCiviles { get; set; }
        public virtual Estratos Estratos { get; set; }
        public virtual Fondos Fondos { get; set; }
        public virtual Fondos Fondos1 { get; set; }
        public virtual Fondos Fondos2 { get; set; }
        public virtual Terceros Terceros { get; set; }
        public virtual TipoIdentificacion TipoIdentificacion { get; set; }
        public virtual TiposContrato TiposContrato { get; set; }
        public virtual Turnos Turnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AusentismoTiempos> AusentismoTiempos { get; set; }
    }
}
