//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fondos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fondos()
        {
            this.Empleados = new HashSet<Empleados>();
            this.Empleados1 = new HashSet<Empleados>();
            this.Empleados2 = new HashSet<Empleados>();
        }
    
        public int IntFondoID { get; set; }
        public string StrCodigo { get; set; }
        public string StrDescripcion { get; set; }
        public string StrNit { get; set; }
        public Nullable<int> IntTipoFondoID { get; set; }
        public Nullable<bool> BitActivo { get; set; }
    
        public virtual TiposFondo TiposFondo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados2 { get; set; }
    }
}
