//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListasDeVerificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListasDeVerificacion()
        {
            this.ListasDeVerificacion_Requisitos = new HashSet<ListasDeVerificacion_Requisitos>();
        }
    
        public int IntListaVerificacionID { get; set; }
        public int IntAuditoriaDetalleID { get; set; }
        public int IntPlantillaDetalleID { get; set; }
        public string StrTitulo { get; set; }
        public string StrHallazgo { get; set; }
        public string StrHallazgoEnInforme { get; set; }
        public bool BitNoConformidad { get; set; }
        public bool BitConformidad { get; set; }
        public bool BitObservacion { get; set; }
        public bool BitEstado { get; set; }
        public Nullable<System.DateTime> DatFechaEnQueAudita { get; set; }
    
        public virtual AuditoriasDetalle AuditoriasDetalle { get; set; }
        public virtual PlantillasListasDeVerificacionDetalle PlantillasListasDeVerificacionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListasDeVerificacion_Requisitos> ListasDeVerificacion_Requisitos { get; set; }
    }
}
