//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modulos()
        {
            this.ModulosDetalle = new HashSet<ModulosDetalle>();
        }
    
        public int IntModuloID { get; set; }
        public string StrModulo { get; set; }
        public string StrDescripcion { get; set; }
        public string StrIcono { get; set; }
        public Nullable<byte> TIntOrden { get; set; }
        public Nullable<bool> BitActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulosDetalle> ModulosDetalle { get; set; }
    }
}
