//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulosDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModulosDetalle()
        {
            this.ModulosPorRol = new HashSet<ModulosPorRol>();
        }
    
        public int IntModuloDetalleID { get; set; }
        public Nullable<int> IntModuloID { get; set; }
        public string StrModuloDetalle { get; set; }
        public string StrDescripcion { get; set; }
        public string StrControlador { get; set; }
        public string StrAccion { get; set; }
        public string StrIcono { get; set; }
        public Nullable<byte> TIntOrden { get; set; }
        public Nullable<System.DateTime> DatFechaCreacion { get; set; }
        public Nullable<bool> BitActivo { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulosPorRol> ModulosPorRol { get; set; }
    }
}
