//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Normas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Normas()
        {
            this.Auditorias_Normas = new HashSet<Auditorias_Normas>();
            this.ElementosComunes_Normas = new HashSet<ElementosComunes_Normas>();
            this.Terceros_Normas = new HashSet<Terceros_Normas>();
            this.Numerales = new HashSet<Numerales>();
            this.Terceros_SistemasDeGestion_Normas = new HashSet<Terceros_SistemasDeGestion_Normas>();
        }
    
        public int IntNormaID { get; set; }
        public string StrCodigo { get; set; }
        public string StrDescripcion { get; set; }
        public int IntTipoCriterio { get; set; }
        public Nullable<bool> BitActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditorias_Normas> Auditorias_Normas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementosComunes_Normas> ElementosComunes_Normas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terceros_Normas> Terceros_Normas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Numerales> Numerales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terceros_SistemasDeGestion_Normas> Terceros_SistemasDeGestion_Normas { get; set; }
    }
}
