//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numerales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Numerales()
        {
            this.ElementosComunes_Detalle_Numerales = new HashSet<ElementosComunes_Detalle_Numerales>();
            this.PlantillasListasDeVerificacion_Numerales = new HashSet<PlantillasListasDeVerificacion_Numerales>();
            this.ListasDeVerificacion_Requisitos = new HashSet<ListasDeVerificacion_Requisitos>();
        }
    
        public int IntNumeralID { get; set; }
        public string StrCodigo { get; set; }
        public string StrDescripcion { get; set; }
        public string StrInterpretacion { get; set; }
        public int IntNormaID { get; set; }
        public Nullable<bool> BitActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementosComunes_Detalle_Numerales> ElementosComunes_Detalle_Numerales { get; set; }
        public virtual Normas Normas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantillasListasDeVerificacion_Numerales> PlantillasListasDeVerificacion_Numerales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListasDeVerificacion_Requisitos> ListasDeVerificacion_Requisitos { get; set; }
    }
}
