//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantillasListasDeVerificacionDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlantillasListasDeVerificacionDetalle()
        {
            this.PlantillasListasDeVerificacion_Numerales = new HashSet<PlantillasListasDeVerificacion_Numerales>();
            this.ListasDeVerificacion = new HashSet<ListasDeVerificacion>();
        }
    
        public int IntPlantillaDetalleID { get; set; }
        public int IntProcesoID { get; set; }
        public string StrTitulo { get; set; }
        public Nullable<int> IntOrden { get; set; }
        public bool BitEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantillasListasDeVerificacion_Numerales> PlantillasListasDeVerificacion_Numerales { get; set; }
        public virtual Procesos Procesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListasDeVerificacion> ListasDeVerificacion { get; set; }
    }
}
