//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantillasListasDeVerificacion_Numerales
    {
        public int IntID { get; set; }
        public int IntPlantillaDetalleID { get; set; }
        public int IntNumeralID { get; set; }
    
        public virtual Numerales Numerales { get; set; }
        public virtual PlantillasListasDeVerificacionDetalle PlantillasListasDeVerificacionDetalle { get; set; }
    }
}
