//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procesos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Procesos()
        {
            this.Auditorias_Procesos = new HashSet<Auditorias_Procesos>();
            this.PlantillasListasDeVerificacionDetalle = new HashSet<PlantillasListasDeVerificacionDetalle>();
            this.AuditoriasDetalle = new HashSet<AuditoriasDetalle>();
        }
    
        public int IntProcesoID { get; set; }
        public string StrCodigo { get; set; }
        public string StrDescripcion { get; set; }
        public int IntTerceroClienteID { get; set; }
        public Nullable<int> IntProcesoOrigen { get; set; }
        public bool BitActivo { get; set; }
        public int IntMacroProceso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditorias_Procesos> Auditorias_Procesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantillasListasDeVerificacionDetalle> PlantillasListasDeVerificacionDetalle { get; set; }
        public virtual Terceros_Clientes Terceros_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriasDetalle> AuditoriasDetalle { get; set; }
    }
}
