//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistemasDeGestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SistemasDeGestion()
        {
            this.DocumentosDiagnostico = new HashSet<DocumentosDiagnostico>();
            this.DocumentosDiagnosticoPasos = new HashSet<DocumentosDiagnosticoPasos>();
            this.Terceros_SistemasDeGestion = new HashSet<Terceros_SistemasDeGestion>();
        }
    
        public string StrCodigoID { get; set; }
        public string StrDescripcion { get; set; }
        public string StrIcono { get; set; }
        public byte TIntOrden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDiagnostico> DocumentosDiagnostico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDiagnosticoPasos> DocumentosDiagnosticoPasos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terceros_SistemasDeGestion> Terceros_SistemasDeGestion { get; set; }
    }
}
