//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terceros_Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terceros_Clientes()
        {
            this.Auditorias = new HashSet<Auditorias>();
            this.Procesos = new HashSet<Procesos>();
        }
    
        public int IntTerceroClienteID { get; set; }
        public int IntTerceroID { get; set; }
        public string StrIdentificacion { get; set; }
        public Nullable<int> IntDV { get; set; }
        public string StrNombre { get; set; }
        public string StrDireccion { get; set; }
        public string StrEmail { get; set; }
        public int IntCiudadID { get; set; }
        public string StrTelefono { get; set; }
        public string StrPaginaWeb { get; set; }
        public Nullable<System.DateTime> DatFechaIngreso { get; set; }
        public string StrRepresentanteLegal { get; set; }
        public string StrRutaImagen { get; set; }
        public bool BitEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditorias> Auditorias { get; set; }
        public virtual Ciudades Ciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procesos> Procesos { get; set; }
        public virtual Terceros Terceros { get; set; }
    }
}
