//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terceros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terceros()
        {
            this.Areas = new HashSet<Areas>();
            this.AspNetTerceroRoles = new HashSet<AspNetTerceroRoles>();
            this.Ausentismo = new HashSet<Ausentismo>();
            this.Cargos = new HashSet<Cargos>();
            this.CentrosDeTrabajo = new HashSet<CentrosDeTrabajo>();
            this.ConfiguracionPorTercero = new HashSet<ConfiguracionPorTercero>();
            this.DocumentosDiagnostico = new HashSet<DocumentosDiagnostico>();
            this.Terceros_Normas = new HashSet<Terceros_Normas>();
            this.Terceros_SistemasDeGestion = new HashSet<Terceros_SistemasDeGestion>();
            this.TercerosUsuarios = new HashSet<TercerosUsuarios>();
            this.Terceros_Clientes = new HashSet<Terceros_Clientes>();
            this.Empleados = new HashSet<Empleados>();
            this.AusentismoTiempos = new HashSet<AusentismoTiempos>();
            this.AusentismoVariables = new HashSet<AusentismoVariables>();
        }
    
        public int IntTerceroID { get; set; }
        public string StrIdentificacion { get; set; }
        public Nullable<int> IntDV { get; set; }
        public string StrNombre { get; set; }
        public string StrDireccion { get; set; }
        public string StrEmail { get; set; }
        public Nullable<int> IntCiudadID { get; set; }
        public string StrTelefono { get; set; }
        public string StrPaginaWeb { get; set; }
        public Nullable<System.DateTime> DatFechaIngreso { get; set; }
        public string StrSigla { get; set; }
        public string StrHabilitacion { get; set; }
        public string StrActividadEconomica { get; set; }
        public string StrSede { get; set; }
        public string StrRepresentanteLegal { get; set; }
        public string StrRutaImagen { get; set; }
        public Nullable<bool> OpcEstado { get; set; }
        public int IntNumeroEmpleados { get; set; }
        public int IntContratistasConductores { get; set; }
        public int IntNumeroDeVehiculos { get; set; }
        public string StrNivelID { get; set; }
        public string StrNivelDeRiesgoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Areas> Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTerceroRoles> AspNetTerceroRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ausentismo> Ausentismo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargos> Cargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentrosDeTrabajo> CentrosDeTrabajo { get; set; }
        public virtual Ciudades Ciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfiguracionPorTercero> ConfiguracionPorTercero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDiagnostico> DocumentosDiagnostico { get; set; }
        public virtual Niveles Niveles { get; set; }
        public virtual NivelesDeRiesgo NivelesDeRiesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terceros_Normas> Terceros_Normas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terceros_SistemasDeGestion> Terceros_SistemasDeGestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TercerosUsuarios> TercerosUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terceros_Clientes> Terceros_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AusentismoTiempos> AusentismoTiempos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AusentismoVariables> AusentismoVariables { get; set; }
    }
}
