//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TercerosUsuarios
    {
        public int IntRegistroID { get; set; }
        public Nullable<int> IntTerceroID { get; set; }
        public string StrUsuarioNombre { get; set; }
        public string StrUsuarioEmail { get; set; }
        public Nullable<bool> OpcEmailEnviado { get; set; }
        public Nullable<bool> OpcEstado { get; set; }
    
        public virtual Terceros Terceros { get; set; }
    }
}
