//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terceros_SistemasDeGestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terceros_SistemasDeGestion()
        {
            this.Terceros_SistemasDeGestion_Normas = new HashSet<Terceros_SistemasDeGestion_Normas>();
        }
    
        public int IntRegistroID { get; set; }
        public int IntTerceroID { get; set; }
        public string StrSistemaDeGestionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terceros_SistemasDeGestion_Normas> Terceros_SistemasDeGestion_Normas { get; set; }
        public virtual SistemasDeGestion SistemasDeGestion { get; set; }
        public virtual Terceros Terceros { get; set; }
    }
}
