//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Across.ArchivosDeRecurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoConfiguracion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoConfiguracion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Across.ArchivosDeRecurso.RecursoConfiguracion", typeof(RecursoConfiguracion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha detectado la configuración necesaria para realizar el envío del correo, por favor comuniquese con el usuario admnistrador..
        /// </summary>
        public static string msnSinConfiguracion {
            get {
                return ResourceManager.GetString("msnSinConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha detectado un email en el contrato actual del cliente, por favor revisar..
        /// </summary>
        public static string msnSinEmailContrato {
            get {
                return ResourceManager.GetString("msnSinEmailContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha configurado el correo remitente, por favor comuniquese con el usuario administrador..
        /// </summary>
        public static string msnSinEmailFrom {
            get {
                return ResourceManager.GetString("msnSinEmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha configurado el servidor de correos, por favor comuniquese con el usuario administrador..
        /// </summary>
        public static string msnSinHost {
            get {
                return ResourceManager.GetString("msnSinHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha configurado el puerto para el envio del correo, por favor comuniquese con el usuario administrador..
        /// </summary>
        public static string msnSinPuerto {
            get {
                return ResourceManager.GetString("msnSinPuerto", resourceCulture);
            }
        }
    }
}
