//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Across.ArchivosDeRecurso {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoActas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoActas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Across.ArchivosDeRecurso.RecursoActas", typeof(RecursoActas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El evento ya tiene registrada un acta de visita..
        /// </summary>
        public static string msnActaYaExiste {
            get {
                return ResourceManager.GetString("msnActaYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aún no se ha generado un acta para ser enviada. Para generarla debe dar click en el boton Acta de visita..
        /// </summary>
        public static string msnSinActa {
            get {
                return ResourceManager.GetString("msnSinActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para este tipo de visitas no está permitido generar actas de visita..
        /// </summary>
        public static string msnSoporte {
            get {
                return ResourceManager.GetString("msnSoporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El acta debe tener temas en la sección de orden del día para poder ser enviada por Email..
        /// </summary>
        public static string msnValidarExisteTemas {
            get {
                return ResourceManager.GetString("msnValidarExisteTemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay visitas programadas.
        /// </summary>
        public static string msnVisitas {
            get {
                return ResourceManager.GetString("msnVisitas", resourceCulture);
            }
        }
    }
}
